move_directly_action_node:
  ros__parameters:
    waypoints: ["room1","room2","room3","room4","room5","room6","room7","room8","room9","room10",
                "zone1","zone2","zone3","zone4","zone5","zone6","zone7","zone8","zone9","zone10",
                "zone11","zone12","zone13","zone14","zone15","zone16","zone17","zone18","zone19A","zone19B","zone20A","zone20B",
                "corridor1","corridor2","corridor3","corridor4","corridor5","corridor6","corridor7","corridor8","corridor9"]
    room1: [-9.3,-21.7]
    room2: [-9.2,-7.6]
    room3: [-10.9,4.3]
    room4: [-11.9,9.2]
    room5: [-8.6,13.4]
    room6: [-5.4,16.9]
    room7: [3.6,17.0]
    room8: [6.9,13.3]
    room9: [9.4,9.5]
    room10: [9.3,4.4]
    room11: [6.9,-5.7]
    room12: [7.2,-19.3]
    room13: [-3.7,-18.0]
    room14: [-2.7,-12.5]
    room15: [-2.1,-4.0]
    room16: [1.5,-18.0]
    room17: [0.7,-12.3]
    room18: [0.29,-3.8]
    room19: [-11.84,-29.0]
    room20: [-0.0,-28.8]

    zone1: [-6.5, -24.1]
    zone2: [-6.5, -9.9]
    zone3: [-9.3, 3.8]
    zone4: [-9.2,10.3]
    zone5: [-7.5,10.3]
    zone6: [-6.0,13.3]
    zone7: [4.3,13.4]
    zone8: [5.7,10.3]
    zone9: [7.4,10.1]
    zone10: [7.4,3.8]
    zone11: [4.8,-10.0]
    zone12: [4.9,-23.9]
    zone13: [-3.7,-16.2]
    zone14: [-3.7,-10.1]
    zone15: [-3.8,-0.2]
    zone16: [1.7,-16.2]
    zone17: [1.8,-10.4]
    zone18: [1.8,-0.3]
    zone19A: [-8.4,-33.6]
    zone19B: [-6.7,-25.9]
    zone20A: [-3.5,-33.7]
    zone20B: [4.5,-26.3]

    corridor1: [4.1,-12.5]
    corridor2: [-6.0,-12.3]
    corridor3: [-0.9,-25.6]
    corridor4: [-1.0,-15.5]
    corridor5: [-1.8,-9.5]
    corridor6: [-3.4,-0.3]
    corridor7: [-1.0,11.0]
    corridor8: [0.4,14.8]
    corridor9: [-0.7,-34.4]


    
move_through_action_node:
  ros__parameters:
    waypoints: ["room1","room2","room3","room4","room5","room6","room7","room8","room9","room10",
                "zone1","zone2","zone3","zone4","zone5","zone6","zone7","zone8","zone9","zone10",
                "zone11","zone12","zone13","zone14","zone15","zone16","zone17","zone18","zone19A","zone19B","zone20A","zone20B",
                "corridor1","corridor2","corridor3","corridor4","corridor5","corridor6","corridor7","corridor8","corridor9"]

    room1: [-9.3,-21.7]
    room2: [-9.2,-7.6]
    room3: [-10.9,4.3]
    room4: [-11.9,9.2]
    room5: [-8.6,13.4]
    room6: [-5.4,16.9]
    room7: [3.6,17.0]
    room8: [6.9,13.3]
    room9: [9.4,9.5]
    room10: [9.3,4.4]
    room11: [6.9,-5.7]
    room12: [7.2,-19.3]
    room13: [-3.7,-18.0]
    room14: [-2.7,-12.5]
    room15: [-2.1,-4.0]
    room16: [1.5,-18.0]
    room17: [0.7,-12.3]
    room18: [0.29,-3.8]
    room19: [-9.5,-27.5]
    room20: [-0.0,-28.8]

    zone1: [-6.5, -24.1]
    zone2: [-6.5, -9.9]
    zone3: [-9.3, 3.8]
    zone4: [-9.2,10.3]
    zone5: [-7.5,10.3]
    zone6: [-6.0,13.3]
    zone7: [4.3,13.4]
    zone8: [5.7,10.3]
    zone9: [7.4,10.1]
    zone10: [7.4,3.8]
    zone11: [4.8,-10.0]
    zone12: [4.9,-23.9]
    zone13: [-3.7,-16.2]
    zone14: [-3.7,-10.1]
    zone15: [-3.8,-0.2]
    zone16: [1.7,-16.2]
    zone17: [1.8,-10.4]
    zone18: [1.8,-0.3]
    zone19A: [-8.4,-33.6]
    zone19B: [-6.7,-25.9]
    zone20A: [-3.5,-33.7]
    zone20B: [4.5,-26.3]

    corridor1: [4.1,-12.5]
    corridor2: [-6.0,-12.3]
    corridor3: [-0.9,-25.6]
    corridor4: [-1.0,-15.5]
    corridor5: [-1.8,-9.5]
    corridor6: [0.0,0.0]
    corridor7: [-1.0,11.0]
    corridor8: [0.4,14.8]
    corridor9: [-0.7,-34.4]

  


