move_directly:
  ros__parameters:
    waypoints: ["room1","room2","room3","room4","room5","room6","room7","room8","room9","room10",
                "zone1","zone2","zone3","zone4","zone5","zone6","zone7","zone8","zone9","zone10",
                "zone11","zone12","zone13","zone14","zone15","zone16","zone17","zone18","zone19A","zone19B","zone20A","zone20B"
                "corridor1","corridor2","corridor3","corridor4","corridor5","corridor6","corridor7","corridor8","corridor9"]
    room1: [-7.5,-20.2]
    room2: [-11.7,-8.2]
    room3: [-13.2,3.3]
    room4: [-11.36,8.8]
    room5: [-11.2,12.2]
    room6: [-7.8,15.4]
    room7: [1.28,15.45]
    room8: [4.9,11.5]
    room9: [7.0,8.1]
    room10: [7.1,3.1]
    room11: [5.5,-7.7]
    room12: [5.2,-22.7]
    room13: [-5.3,-24.3]
    room14: [-5.6,-14.0]
    room15: [-5.0,-5.6]
    room16: [-0.8,-19.6]
    room17: [-1.5,-13.3]
    room18: [-2.0,-4.5]
    room19: [-11.84,-29.0]
    room20: [-4.0,-31.2]

    zone1: [-9.6,-25.4]
    zone2: [-8.7,-11.3]
    zone3: [-9.2,2.44]
    zone4: [-10.1,8.7]
    zone5: [-9.5,8.7]
    zone6: [-8.2,11.4]
    zone7: [1.5,11.51]
    zone8: [3.0,8.4]
    zone9: [4.6,8.6]
    zone10: [4.4,2.6]
    zone11: [1.9,-11.5]
    zone12: [2.3,-25.5]
    zone13: [-6.1,-17.2]
    zone14: [-6.2,-11.4]
    zone15: [-6.0,-0.8]
    zone16: [-0.5,-17.3]
    zone17: [-0.5,-11.3]
    zone18: [-0.3,-1.2]
    zone19A: [-11.0,-35.8]
    zone19B: [-8,2,-27.0]
    zone20A: [-5.7,-35.6]
    zone20B: [2.0,-27.0]

    corridor1: [1.7,-16.7]
    corridor2: [-7.8,-6.0]
    corridor3: [-3.5,-26.8]
    corridor4: [-3.4,-16.9]
    corridor5: [-4.1,-11.1]
    corridor6: [-3.4,-0.3]
    corridor7: [-3.1,9.0]
    corridor8: [-2.7,13.3]
    corridor9: [-8.4,-36.0]


    
move_through:
  ros__parameters:
    waypoints: ["room1","room2","room3","room4","room5","room6","room7","room8","room9","room10",
                "zone1","zone2","zone3","zone4","zone5","zone6","zone7","zone8","zone9","zone10",
                "zone11","zone12","zone13","zone14","zone15","zone16","zone17","zone18","zone19A","zone19B","zone20A","zone20B"
                "corridor1","corridor2","corridor3","corridor4","corridor5","corridor6","corridor7","corridor8","corridor9"]

    room1: [-7.5,-20.2]
    room2: [-11.7,-8.2]
    room3: [-13.2,3.3]
    room4: [-11.36,8.8]
    room5: [-11.2,12.2]
    room6: [-7.8,15.4]
    room7: [1.28,15.45]
    room8: [4.9,11.5]
    room9: [7.0,8.1]
    room10: [7.1,3.1]
    room11: [5.5,-7.7]
    room12: [5.2,-22.7]
    room13: [-5.3,-24.3]
    room14: [-5.6,-14.0]
    room15: [-5.0,-5.6]
    room16: [-0.8,-19.6]
    room17: [-1.5,-13.3]
    room18: [-2.0,-4.5]
    room19: [-11.8,-29.0]
    room20: [-4.0,-31.2]

    zone1: [-9.6,-25.4]
    zone2: [-8.7,-11.3]
    zone3: [-9.2,2.44]
    zone4: [-10.1,8.7]
    zone5: [-9.5,8.7]
    zone6: [-8.2,11.4]
    zone7: [1.5,11.51]
    zone8: [3.0,8.4]
    zone9: [4.6,8.6]
    zone10: [4.4,2.6]
    zone11: [1.9,-11.5]
    zone12: [2.3,-25.5]
    zone13: [-6.1,-17.2]
    zone14: [-6.2,-11.4]
    zone15: [-6.0,-0.8]
    zone16: [-0.5,-17.3]
    zone17: [-0.5,-11.3]
    zone18: [-0.3,-1.2]
    zone19A: [-11.0,-35.8]
    zone19B: [-8,2,-27.0]
    zone20A: [-5.7,-35.6]
    zone20B: [2.0,-27.0]

    corridor1: [1.7,-16.7]
    corridor2: [-7.8,-6.0]
    corridor3: [-3.5,-26.8]
    corridor4: [-3.4,-16.9]
    corridor5: [-4.1,-11.1]
    corridor6: [-3.4,-0.3]
    corridor7: [-3.1,9.0]
    corridor8: [-2.7,13.3]
    corridor9: [-8.4,-36.0]

  


